/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xxun.watch.xunpet.jni;

public class SoundStretch {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SoundStretch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SoundStretch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SoundStretchJNI.deleteSoundStretch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SoundStretch() {
    this(SoundStretchJNI.newSoundStretch(), true);
  }

  public void process(String inFilename, String outFilename, float tempoDelta, float pitchDelta, float rateDelta) {
	  SoundStretchJNI.processSoundStretch(swigCPtr, this, inFilename, outFilename, tempoDelta, pitchDelta, rateDelta);
  }

}
